repos:
-   repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
    -   id: flake8
        types: [python]
        args: ["--max-line-length=79"]
        exclude: ^(.git|__pycache__|.pytest_cache|venv|docs|alembic)
-   repo: https://github.com/PyCQA/autoflake
    rev: "v2.3.1"
    hooks:
    -   id: autoflake
        types: [python]
        exclude: ^(.git|__pycache__|.pytest_cache|venv|docs|alembic)
-   repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
    -   id: black
        types: [python]
        args: ["--line-length=79"]
        exclude: ^(.git|__pycache__|.pytest_cache|venv|docs|alembic)
